language: node_js
node_js:
  - "0.10"

script: "echo to infinity and beyond!"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: s3
  access_key_id: AKIAJOLWV5HPI2CLKW7Q
  secret_access_key:
    secure: pYkj+Cx5XIyO8FyQuZIrEuJR14AUUzIH8u8S+EkSDs/xLRSuPWbu8cU00WFxoZegGd/30gs86J3+nRVT+6HU/NBj14ZjNtPI3WN2F9wVT/QvwHiTN+Zwix6gfI+0PYVWRxleg/jL58WleBgZJDAvqfvzG7yNvswjwXuDDX+v95o=
  bucket: joeflasher.com
  acl: public_read
  on:
    repo: jflasher/joeflasher.com
    branch: master